# -*- coding: utf-8 -*-
"""Append

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHrU8hPUX9p7aqx2QehSSfgdqQAjPAww
"""

#13.  Compute given Num_tuple=(5,6,8,3,9,1) to get desired output.
#     Output : Out_list=[5,30,240,720,6480,6480]  

n=(5,6,8,3,9,1)
Out_list=[]
Out_list.append(n[0])
for i in range(len(n)-1):
    m=Out_list[i]*t[i+1]
    Out_list.append(m)
print("Out_list=",Out_list)

