# -*- coding: utf-8 -*-
"""Leap year

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aqhw38XqCCUCSA_mvgZcXw4VA6hwPwvy
"""

#3. Write a program that reads a year from the user and displays a message indicating whether year is leap year or not.

year=int(input("Enter the year:"))
if(year%4==0 and year%100!=0 or year%400==0):
    print("{} The entered year is leap year".format(year))
else:
    print("{} The entered year is not a leap year".format(year))

