# -*- coding: utf-8 -*-
"""list of its digits

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHrU8hPUX9p7aqx2QehSSfgdqQAjPAww
"""

#14.  Write a Python code that takes a number and returns a list of its digits. So for 586392 it should return [5,8,6,3,9,2].

number=input("Enter a number: ")
list=[]
for n in range(len(number)):
    list.append(number[n])
print(list)

