# -*- coding: utf-8 -*-
"""palindrome or not

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHrU8hPUX9p7aqx2QehSSfgdqQAjPAww
"""

#2. Take a string from end user and check if the value is palindrome or not.

s=input("Enter a string:")
if(s==s[::-1]):
    print("Given string {} is palindrome".format(s))
else:
    print("Given string {} is not palindrome".format(s))

