# -*- coding: utf-8 -*-
"""product of a list of numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHrU8hPUX9p7aqx2QehSSfgdqQAjPAww
"""

#11. Compute product of a list of numbers [45,3,2,89,72,1,10,7]
#    Output: 121111200

list=[45,3,2,89,72,1,10,7]
n=1
for i in range(len(list)):
    n=n*list[i]
print(n)

