# -*- coding: utf-8 -*-
"""single integer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHrU8hPUX9p7aqx2QehSSfgdqQAjPAww
"""

#7. Take a list of integers as an argument, and converts it into a single integer (return the integer).
#   input:[11,33,50]
#   output:113350

l=[11,33,50]
for i in l:
  print(i,end="")

