# -*- coding: utf-8 -*-
"""Space to Hyphen

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aqhw38XqCCUCSA_mvgZcXw4VA6hwPwvy
"""

#4. Space to Hyphen problem
#   Take a string as input, and replaces spaces " " with hyphens "-", and returns a string.
#   Input: "This program converts spaces into hyphen"
#   Output: "This-program-converts-spaces-into-hyphen"

n=input("Enter a string : ")
print(n.replace(' ','-'))

