# -*- coding: utf-8 -*-
"""Substring Check

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHrU8hPUX9p7aqx2QehSSfgdqQAjPAww
"""

#16.  Substring Check (Bug Funny)
#     Given two binary strings, A (of length 10) and B (of length 5), output 1 if B is a substring of A and 0 otherwise.
#     First two lines of input:
#     1010110010          10110
#     1110111011           10011
#     First two lines of output:
#     1
#     0

t=int(input())
for i in range(t):
  A,B=input("Enter A string and B string : ").split()
  if B in A:
    print("1")
  else:
    print("0")

