# -*- coding: utf-8 -*-
"""total number of seconds

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHrU8hPUX9p7aqx2QehSSfgdqQAjPAww
"""

#8. Units of Time
#   Create a program that reads duration from the user as a number of days, hours, minutes, and seconds. 
#   Compute and display the total number of seconds represented by this duration.

secondspermin=60
secondsperhour=3600
secondsperday=86400
days=int(input("Enter the number of Days: "))
hours=int(input("Enter the number of Hours: "))
minutes=int(input("Enter the number of Minutes: "))
seconds=int(input("Enter the number of Seconds: "))
totalseconds=days*secondsperday
totalseconds=totalseconds+(hours*secondsperhour)
totalseconds=totalseconds+(minutes*secondspermin)
totalseconds=totalseconds+seconds
print("Total number of seconds = ","%d"%(totalseconds))

