# -*- coding: utf-8 -*-
"""Triangle Area

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aqhw38XqCCUCSA_mvgZcXw4VA6hwPwvy
"""

#1. Given the lengths of three sides of a triangle, calculate the area of the triangle.

a=float(input("Enter length of 1st side of a triangle:"))  
b=float(input("Enter length of 2nd side of a triangle:"))  
c=float(input("Enter length of 3rd side of a triangle:"))  
if(a+b>c):
  s=(a+b+c)/2  
  area=(s*(s-a)*(s-b)*(s-c))**(1/2)
  print("The area of the triangle is= ", round(area,2))
else:
  print("The triangle is not possible")

