# -*- coding: utf-8 -*-
"""Unique Sort

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aqhw38XqCCUCSA_mvgZcXw4VA6hwPwvy
"""

#5. Unique Sort Problem.
#   Take a string as input that accepts a comma separated sequence of words as input and prints the unique words in sorted form (alphanumerically).
#   Input: orange,white,red,cyan,green,magenta,cyan,pink,white
#   Output: cyan,green,magenta,orange,pink,red,white

str=input("Enter a string: ")
s=str.split()
s.sort()
list(s)
set(s)

